var caption_text = {'Person33_42': 'Tortoise racing for life',
 'Person33_17': 'Be the pop of color that can illuminate the monochromatic lives of others.',
 'Person33_31': 'Tortoise at Gym building Muscles',
 'Person33_53': 'Rolling dice in a stable position',
 'Person33_1': 'The things are not always where you think they are, even if you see them with your own eyes.\n',
 'Person33_34': 'Tortoise is trying to blow the whistle ',
 'Person33_61': 'Rolling dice showing its magic number',
 'Person33_56': 'Tortoise Dragging Rocket to the launch pad',
 'Person33_4': 'Six might be considered a lucky number by common people but for a mathematician it is the smallest perfect number.\n',
 'Person33_39': 'Slow tortoise in a pace to meet its friends on its bike',
 'Person33_47': 'Tortoise in Group confronting Evil Tortoise',
 'Person33_9': 'Keep your eyes on the stars, and your feet on the ground.',
 'Person33_12': 'More than 1 billion rural people depend on forests to some extent, and over 90 percent of people living in extreme poverty depend on forests for all or part of their livelihoods',
 'Person33_40': 'Rocket in colorful Multiverse',
 'Person33_15': 'As one climbs the stairs of success in life, luck plays an important factor in deciding life’s path. Probability and possibility are added coefficients to hard work and perseverance when it comes to calculating life’s success equation.',
 'Person33_3': 'Why can’t humans hear a dog whistle? \n',
 'Person33_33': 'Tortoise trying hard to get his number',
 'Person33_51': 'NASA astronaut in Made in China spacecraft… isn’t something fishy?',
 'Person33_48': 'Tortoise looking to climb the tower',
 'Person33_6': 'Someone tried to blow up these chains with a toy rocket… even he knows the earth is not flat.\n',
 'Person33_36': 'Laborious tortoise… trying to show its strengths',
 'Person33_54': 'Tortoise rising high after climbing the tower',
 'Person33_45': 'In a hurry to meet the finish line. Cheerleader awaiting them',
 'Person33_59': 'Rocket in the white sky after launch but with a red tail',
 'Person33_35': 'Tortoise fed up of its slow moving life…..committing suicide',
 'Person33_60': 'Green Tortoise trying to save its friend from evil white Tortoise',
 'Person33_57': 'Rocket Ignition Started t-1 sec and it is monitored by the Mystery man',
 'Person33_29': 'Tortoise with wings',
 'Person33_5': 'In case you are waiting so long for the elevator, please feel free to use the whistle.',
 'Person33_38': 'Slow motion race…. let’s see who comes first',
 'Person33_46': 'So sweet tired little tortoise got its ride back to home',
 'Person33_8': 'I’m pretty sure everything in this picture somehow comes from oil. Plastic whistle, the dice, the missile, color on the wall and of course the electricity.',
 'Person33_24': 'An assembly of random items that resulted in something meaningful.',
 'Person33_13': 'Nature is a miracle we depend upon.',
 'Person33_43': 'Tortoise in an entertaining world… trying to enjoy the worldly pleasures',
 'Person33_21': 'Identify the artificial things even though they might look like they are the same.',
 'Person33_30': 'Tortoise with a girl in pub',
 'Person33_52': 'Tortoises having party',
 'Person33_49': 'White tortoise is happy of its new camouflage ',
 'Person33_7': 'May your coffee be strong and your life be colorful.',
 'Person33_37': 'Astronaut ready to invade into space with its craft',
 'Person33_55': 'Tortoise walking in Circus of uncertainty',
 'Person33_44': 'Emergence of a new leader',
 'Person33_58': 'Tortoise in Shock to see the balanced Dice',
 'Person33_41': 'Rocket ready to take off t-10 sec',
 'Person33_23': 'Balance is a delicate thing. One gust of wind and things can go downhill.',
 'Person33_14': 'Getting perspective in life and planning isn’t easy.  It is said that life is what happens when you keep planning it. God rolls a dice and your life changes in an instant.',
 'Person33_2': 'Globally, we generate about 1.3 billion tons of trash per year. In Germany alone, this amounts to a whopping 3 million tons of plastic packaging waste annually.\n',
 'Person33_32': 'Tortoise chained in slavery',
 'Person33_50': 'Red spiraled green tortoise’s new look...ready for fashion show\n',
 'Person35_11': 'My cats enjoyed playing soccer with this eyeball until it rolled under the oven\n',
 'Person35_4': 'Green turtles are a good investment Buy now!\n',
 'Person35_6': 'Spring in my spinner broke\n',
 'Person35_3': 'You come home to find a single lit pink candle on valentines day wyd?\n',
 'Person35_5': 'Yellow cowbell>normal cowbell\n',
 'Person35_2': 'This trophy is a good prize for my win in HotS\n',
 'Person35_7': 'The benefit of the maple leaf pencil is that you dont misspell sorry\n',
 'Person28_5': 'I hang the cowbell onto my schoolbag! I walked home at night along the side of the road. The cowbell rang along with the sound of the wind and the passing cars.\n',
 'Person28_2': 'Actually, the spider is under the protect of the spider web. The spider is waiting the dragonfly to put itself into the web.\n',
 'Person28_4': 'When I came back to the lab tonight, I found an apple hung on the doorknob.\n',
 'Person28_1': 'The dragonfly sees a spider (ring) and wants to eat it as dinner. The dragonfly is confident in itself.\n',
 'Person28_3': 'Sticker box meets the black hair clip. Sticker box: Hey, buddy. Why do you look like a crab? Black hair clip: I was kidnapped! Oh, you are laughing at me! Sticker box: I can only laugh......\n',
 'Person26_1': 'A great day to craft. I wonder how much of a mess I can make today.\n',
 'Person26_4': 'Plague apocalypse survival kit.\n',
 'Person26_3': 'Uh oh. Someone is going to have a bad when they realize they can’t drive home from the park.\n',
 'Person26_5': 'This is as close as I will get to a thunderstorm here. Not missing my soggy home.\n',
 'Person26_2': 'The cat of destruction has struck the innocent again.\n',
 'Person27_12': "My girlfriend is really sweet! But I don't think the pink candle goes well with tiramisu.\n",
 'Person27_4': 'The sun is so bright today, my sunglasses just came in handy.\n',
 'Person27_9': 'Look what we found in the yellow leaves! A rainbow colored bracelet!\n',
 'Person27_1': 'Look what we found in the glasses! A blank 3D printed carabiner!\n',
 'Person27_10': "I was at a party, and you know what's interesting about this party? If you're single you wear a lego bracelet on your left wrist, otherwise on your right hand.\n",
 'Person27_6': 'I suddenly realized how handsome my little tiger looked in these blue sunglasses.\n',
 'Person27_3': "Of all our 3d-printed creations, the black hook is the one we're most proud of.\n",
 'Person27_5': 'Hey! Look! The little tiger in the sunglasses is reading a book!\n',
 'Person27_13': 'I found a cute pumpkin notebook next to sticky notes under the message wall.\n',
 'Person27_8': 'This pink foam hair roller really works! My bangs look great in the morning!\n',
 'Person27_14': 'My cute pumpkin notebook is just the same size as the sticky note.\n',
 'Person27_2': "We've just used a 3D printer to print a black hook that looks strong and can hold tens of kilograms.\n",
 'Person27_7': 'My desk is a mess, with useless sunglasses and the black 3d-printed carabiner.',
 'Person27_11': 'I am wandering who accidentally left his cute Lego bracelet on the grass.\n',
 'Person29_8': "Dropped my pencil and now the tip is broken. Anyone around with a sharpener? Haven't owned one since the seventies...",
 'Person29_5': 'Same question every day! Which coffee should I get? Rolling my classic purple dice to decide. 1-2 is for latte, 3-4 is for espresso and 5-6 flat white. What will it be today? #CoffeeIsLife #QuestionsThatMatter',
 'Person29_10': 'Small victories bring small trophies, but many a mickle makes a muckle. So it now sits enthroned on my desk, shining golden on top of an award certificate of a data analysis challenge.',
 'Person29_2': "While it is a little too big, duck Emma's new red bow with a bell really compliments her bright yellow tone. Also, we can hear the bell when Emma decides to take off from her place on the desk.\n",
 'Person29_14': 'Lunch time! Since our office expanded, its not enough to shout any more, so we use this little whistle to get everyone to go to lunch. And its bright red!',
 'Person29_4': 'Hiking here is great, but you really should have some bear spray with you! I didnt want to carry the heavy bottle around by hand all day, so I was really happy about the nice black carabiner my friend 3D printed for me so I could attach the bottle to my backpack! ',
 'Person29_6': 'I really appreciate the little turquoise glass gems I got as present! They are really smooth and you can juggle them in your hand which is totally relaxing.',
 'Person3_10': '10. unstacking these waxy color sticks was fun on its own.\n',
 'Person3_1': '1. good ideas are like blue orbs\n',
 'Person3_9': '9. There were a lot of colors available\n',
 'Person3_18': '18. If my head was transparent\n',
 'Person3_4': '4. the metal is in focus and this is a great example of depth of field\n',
 'Person3_15': '15. The drawing tool drew itself. Very meta.\n',
 'Person3_22': '22. We made a color fort with a very small interior\n',
 'Person3_12': "12. the paper clip doesn't clip anything other than paper apparently. My apple was not securely held in this bag. 0 of 5 starts. VERY DISAPPOINTED! WOULD NOT RECOMMEND !\n",
 'Person3_3': '3. this paper clip reminds me of the spaceship from Galaga!\n',
 'Person3_6': '6. The banana bell went back on the shelf. It was not my fav.\n',
 'Person3_20': "20. Seems like we're just happy to be taking a break.\n",
 'Person3_17': '17. My back-lit balloon buddy\n',
 'Person3_8': '8. That foil pumpkin on the cover is inspiring me to make some art.\n',
 'Person3_19': "19. Now ballon buddy won't even look at me.\n",
 'Person3_5': '5. In this example our depth of field focuses on the blue ball\n',
 'Person3_14': '14. I sketched a still life of my deflated yellow friend.\n',
 'Person3_23': '23. Packed up my favorite pumpkin sketchbook for the day. Time to go home\n',
 'Person3_11': '11. I made a rainbow mess\n',
 'Person3_7': '7. COLORING TIME!!!\n',
 'Person3_21': "21. Hanging upside will bring a smile to any oval's face\n",
 'Person3_16': '16. These stacked rainbow marks were my favorite\n',
 'Person3_13': '13. is this art or can it go away?\n',
 'Person3_24': "24. I'm not sure how this violent color matchup came to be\n",
 'Person3_2': '2. crystal stones can sometimes be face-melting. Just look at this guy\n',
 'Person37_17': 'Someone dropped a pair of purple sticks on grassland. May I pick them\n',
 'Person37_2': 'The sound of this spinner is quite interesting.\n',
 'Person37_5': "It haven't rained here for a long time. Every day is sunny and I hope for a heavy rain.\n",
 'Person37_22': 'Can I generate electricity from these two pink plastic sticks\n',
 'Person37_8': 'I found a hair roller on the desk.\n',
 'Person37_18': 'My cousin broke my LED spinner by dropping it on a rock. What a bad day!\n',
 'Person37_10': 'I won a cloud and lightning decoration in the spinning game.\n',
 'Person37_13': '"After a bolt of lightning hit the emoji plate, a pink thing appeared. A gift from the god! But what does this mean"\n',
 'Person37_24': "I made a safe dart that won't hurt anyone.\n",
 'Person37_3': 'I found it very fun to play a LED spinner. It shines when rotating. I want to know the mechanism behind.\n',
 'Person37_21': 'Can I shoot the smiley emoji with the dart five meters away\n',
 'Person37_1': 'We are going to watch a football match and cheer for the school team.\n',
 'Person37_14': 'Are these things enough to hold a party\n',
 'Person37_23': 'I want to connect the whistle with gold shiny tape to the LED spinner. It should be very good-looking when they rotate!\n',
 'Person39_3': 'My souvenir from Canada is not very useful until I sharpen it. I had better grab my eye protection in case we have another "incident" with the sharpener like last time...\n',
 'Person39_9': 'I bet I can throw one of these 50 feet and the other 50 meters. And if I hit someone, well, neither is going to hurt.\n',
 'Person39_4': "I spend so much time indoors, it's a wonder I even own a pair of these. I wonder if they help with computer screens?\n",
 'Person39_2': 'Nice to have a black keychain that can listen to the world around me and play back what it heard.\n',
 'Person39_11': "These cards can fit in the palm of my hand and are quite hard to shuffle. That's not the weird part, though: I didn't China had a king.\n",
 'Person39_7': 'This colorful, textured bracelet gets a "thumbs up" from me. I wish there were matching toy bricks, but I will have to settle for this wall.\n',
 'Person39_text8.txt': 'Another noisy crowd in the balcony at symphony hall. I could barely hear the strings, but at least I can listen over and over again thanks to my trusty recorder. \n',
 'Person39_8': 'If you are bored you can throw all of these things, but only one of them can be "thrown on" to look more fashionable.\n',
 'Person31_2': 'The sun shines a lot, the small turtle builds up a big umbrealla with a rainball. He stays there happliy. ',
 'Person31_3': 'Some hours later, his friend Dr.Duck comes - "Hi, Mr Turtle, how\'s things going on?", Said the duck.The turtle answers: "Very good, you see my new sun glasses and umbrealla?" "Cool!"\n',
 'Person31_4': 'The turtle swimmed in a while in the sea, and found a very big diamond! Today is really a lucky day for it.',
 'Person31_1': 'A day of a turtle \n',
 'Person36_8': 'Sports have been cancelled\n',
 'Person40_10': 'The red attracts cats. Watch out!',
 'Person40_6': 'Tienes la llave de mi corazon?',
 'Person40_9': 'the miracle at gatech.edu in eraser form',
 'Person14_5': 'this spinner is fun to watch',
 'Person14_6': 'in minicard bridge doubles are halved',
 'Person14_1': 'prophetic decorations for todays weather',
 'Person14_13': 'my pink candle keeps blowing out in the wind',
 'Person14_9': 'a maple leaf pencil reminds me of home\n',
 'Person13_10': '"Anyone else ever hang their glasses from the door, or is that just me?"\n',
 'Person13_27': '"Teaser for the beach party later, people"\n',
 'Person13_18': 'Glad everyone enjoyed the cupcakes so much that the leftovers ended up on the floor.\n',
 'Person13_22': "I'm going to say he enjoyed the cupcake...\n",
 'Person13_8': "Leftover goodies from the kid's party.\n",
 'Person13_25': 'Small playing cards are the only playing cards.\n',
 'Person13_34': 'One heck of a party for that to end up there...\n',
 'Person13_5': 'Anyone order a loud party?\n',
 'Person13_20': '"Thanks for not throwing this stuff away, guys."\n',
 'Person13_11': 'So excited about my new bird whistle\n',
 'Person13_6': 'Cool shades ready for the day? Check.\n',
 'Person13_37': 'Anyone else hang their sunglasses off their dishwasher? Just me? Thought so.\n',
 'Person13_30': 'Practicing for the casino tonight\n',
 'Person13_9': 'This plate is cool enough to be a decoration\n',
 'Person13_4': 'Ready for poker night tonight\n',
 'Person7_10': 'The scarlet red whistle goes well with dark green leaves.\n',
 'Person7_7': 'Sunshine makes smilies smiley.\n',
 'Person7_2': 'It’s sunny out here. Lucky me. I have my lovely blue sunglasses with me.\n',
 'Person7_15': 'Can I huck this pencil over them buildings?\n',
 'Person7_8': 'Who am I? A calabash with sunglasses.\n',
 'Person7_12': 'All of my belongings today.\n',
 'Person7_5': 'Can I use the sunglasses as swimming goggles?\n',
 'Person7_17': 'Does a table football need a referee with a whistle?\n',
 'Person7_3': '2 leaves & 6 on the dice\n',
 'Person7_14': 'What can a trophy do? Holding my pencil?\n',
 'Person7_11': 'My swimming trophy is in the swimming pool.\n',
 'Person7_6': 'Can you find me? I’m a lonely brown dice on the green grass.\n',
 'Person7_1': 'Paper and a pencil are here. I wanna write but I can’t.\n',
 'Person7_16': 'A brown cube dice with green-blue square tiles.\n',
 'Person7_9': 'I’ve just won a swimming race. Here is my trophy and a whistle I nicked from my coach.\n',
 'Person7_13': 'Could you please help me find my trophy?\n',
 'Person7_4': 'Trophy and sunset by the swimming pool\n',
 'Person24_1': "The World's hardest game of solitaire\n",
 'Person12_6': "I've been in dire need of a new hair clip\n",
 'Person12_12': "Lego bracelets are spring's hottest fashion statement\n",
 'Person12_3': 'Cacti are on the list\n',
 'Person12_15': 'Hopefully this pumpkin can start a vibrant patch\n',
 'Person12_10': 'These noisemakers are the right color for Northwestern games\n',
 'Person12_1': 'This empty yellow bag might blow away from the river wind\n',
 'Person15_7': 'erasing my banana doodle with pink eraser',
 'Person15_13': 'a villainous recording\n',
 'Person15_11': 'tossing a jet ball',
 'Person15_5': 'golden glover ender inciarte tripping over this massive hair roller\n',
 'Person15_3': 'hello world written on the sign',
 'Person15_9': 'braves hofer andruw jones was never seen w/o his trust bird whistle',
 'Person15_1': 'supporting the lads with these noisemaker sticks'}